# Generated by Django 4.0.5 on 2022-06-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3, verbose_name='Название валюты')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='Код ISO')),
                ('iso_title', models.CharField(max_length=3, unique=True, verbose_name='Название ISO')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюта',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True, verbose_name='Номер заказа')),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость в USD')),
                ('shipment_date', models.DateField(verbose_name='Срок Поставки')),
                ('rub_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость в руб.')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-shipment_date',),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Курс валюты')),
                ('nominal', models.IntegerField(verbose_name='Номинал валюты')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата курса')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='orders.currency')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'get_latest_by': ('-date',),
            },
        ),
    ]
